config/routes.rb
Practice1::Application.routes.draw do
  resources :contacts

  root :to => 'pages#home' 

  match '/home', to: 'pages#home'
  match '/portfolio', to: 'pages#portfolio'
  match '/contacts', to: 'contacts#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  attr_accessible :email, :name, :phone, :request, :zip

end


 

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :taken, :title, :url, :url_large

  scope :last_three_photos, -> {order('taken desc').limit(4) }
  scope :portfolio_photos, -> {order('taken desc').limit(12) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

 

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      ContactMailer.service_request(@contact).deliver
      redirect_to(root_path, :notice => "Thanks for getting in touch, we will get back to you soon")
    else
      render :new
    end
  end
 

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

include PhotoGrabber::PhotoRetriever
 
def home
  @latest = Portfolio.last_three_photos
end


def portfolio
  @portfolio = Portfolio.portfolio_photos
end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="container main">

		<div id="slogan" class="clearfix">
			<div class="sixteen columns">
				<div class="slogan">
					<p>If you have <span class="color">any questions</span> <span class="light_gray">don't <br />hesitate</span> to use the form below!</p>
				</div>
			</div>
		</div>
		
		<div class="container">
			<div class="sixteen columns">
				<hr class="line slogan" />
			</div>
		</div>
		
		<div id="page-content" class="full-width container">
			<div class="sixteen columns">
			  <div id="googlemaps" class="google-map google-map-full" style="height:300px"></div>
         <h3 class="gmap-header">Leave us a message</h3>
      </div><!--/sixteen -->
    </div>

    <div class="container">
      <div class="eight columns">

				  <div id="contactForm">
					 <%= form_for @contact, :class => 'form' do |f| %>
  
             <div class="control-group">
               <%= f.label :name,  :class => 'control-label' %>
              <div class="controls">
               <%= f.text_field :name, :id => 'inputName', :class => 'name', :placeholder => 'Enter Name Here...' %>
              <span class="help-inline">Please fill your name</span>
             </div>
           </div>

            <div class="control-group">
              <%= f.label :email, :class => 'control-label' %>
             <div class="controls">
              <%= f.text_field :email, :id => 'inputEmail', :class => 'email', :placeholder => 'Enter Your E-mail Address...' %>
               <span class="help-inline" style="display: none;">Please check your email</span>
             </div>
            </div>

            <div class="control-group">
              <%= f.label :phone, 'Phone Number', :class => 'control-label' %>
             <div class="controls">
              <%= f.text_field :phone, :id => 'inputTel', :class => 'phone', :placeholder => 'Enter Phone Number here' %>
              <span class="help-inline" style="display: none;">Please Check Your Phone Number</span>
             </div>
            </div>

            <div class="control-group">
              <%= f.label :zip, 'Zip Number', :class => 'control-label' %>
             <div class="controls">
              <%= f.text_field :zip, :id => 'inputZip', :class => 'zip', :placeholder => 'Enter Zip Number here' %>
              <span class="help-inline" style="display: none;">Please Check Your Zip Number</span>
             </div>
            </div>

            

          </div><!--/eight columns-->
        </div>

           <div class="eight columns">

            <div class="control-group">   
              <%= f.label :message, :class => 'control-label' %>
               <div class="controls">
                <%= f.text_area :request, :id => 'textarea', :class => 'message', :rows => 10 %>
                 <span class="help-inline" style="display: none;">Please Enter a Message</span>
               </div>
            </div>

             <div class="actions">
              <%= f.submit "Send Message" %>
             </div>
  
         <% end %>
           </div>
         	</div><!--/contact form -->
				</div><!--eight columns-->

			</div><!--/container -->
			


		


<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApUO4ajt4kh5KnLE-zJbdmDKrVf7zqsvA&sensor=false">
    </script>

 <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(38.327347,-77.584454),
          zoom: 10,
          scrollwheel: false,
          draggable: false,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById("googlemaps"),
            mapOptions);

        var marker = new google.maps.Marker({
          position: map.getCenter(),
          map: map,
          title: 'Newbridges Care'
        });

        var center;
        function calculateCenter() {
         center = map.getCenter();
        }
         google.maps.event.addDomListener(map, 'idle', function() {
         calculateCenter();
        });
         google.maps.event.addDomListener(window, 'resize', function() {
         map.setCenter(center);
        });
       }
         </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Wellspring Lawn & Landscape</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
 <body onload="initialize()">
   <div id="wrap">
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>

    <%= render 'shared/header' %>
     
    <%= yield %> 
    <%= render 'shared/footer' %>
     
   </div><!--End wrapper-->
 </body>
</html>
  





  
 

app/views/pages/home.html.erb
<div class="container main">
		<div id="slogan" class="clearfix">
			<div class="sixteen columns">
				<div class="slogan">
					<p>Hello, we are Wellspring <span class="color">Lawn</span> and <span class="color">Landscape</span></p>
				</div>
			</div>
		</div>
		
		<div id="page-content" class="full-width container">
		
			<div class="container">
				<div class="sixteen columns">
					<div class="flexslider">
						<ul class="slides">
							<li>
								<img src="/assets/banner1.jpg" />
								<div class="slide-caption">
									<h3>Example Title 1</h3>
									<p>In school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten burned over Cheryl Tiegs, blown up for Raquel Welch. But when I end up in the hay it's only hay, hey hey.</p>
								</div>
							</li>
							<li>
								<img src="/assets/banner2.jpg" />
								<div class="slide-caption">
									<h3>Example Title 2</h3>
									<p>In school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten burned over Cheryl Tiegs, blown up for Raquel Welch. But when I end up in the hay it's only hay, hey hey.</p>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="container">
				<div class="sixteen columns">
					<p class="recentWork">Welcome to Wellspring Lawn and Landscape. We are a Locally owned and operated company based in the Fredericksburg Area. We service The city of Fredericksburg, Counties of Spotsylvania, Stafford and King George, specializing in turf care maintenance and Landscape Design and Install.</p>
					<p class="recentWork">Please take some time to view some of our more recent projects and don’t hesitate to call or email with all of your Lawn and Landscaping Needs.</p>
					<button class="button">View Portfolio</button>
				</div>
			</div>

			<div class="container">
				<h3 class="recent">Recent Work</h3>
				<% @latest.each do |l| %>
				<div class="four columns">
					<div class="our-work">
						<%= link_to (l.url_large), :class => 'fancybox', :rel => 'group' do %>
             <%= image_tag(l.url_large, size: '220x220') %>
            <% end %>
						<h3 class="recent"><%= truncate(l.title, :length => 20) %></h3>
					</div>
				</div>
				<% end %>
			</div>
				
				
			
			
			<div class="container">
				<div class="sixteen columns mb20">
					<h2 class="recent">Our Services</h2>
					<p class="our-services">Wellspring Lawn and Landscape specializes in turf care and weekly maintenance of your home and garden And Landscape Design and Installs. We're here to transform your lawn into the golf course quality turf you deserve, and your Home into a personal Oasis.</p>

         <p class="our-services">Offering competitive pricing on Mowing and applications of weed killers and fertilizers for your turf as well as Free Estimates for any Landscaping Projects you may desire. Our staff is smart, capable, and ready to serve.</p>
				</div>
				
				<div class="four columns">
					<div class="home-blog">
						<img id="hedges" class="services"/>
							
						<div class="home-blog-post">
							<h3 class="allServices">Hedges and Shrubs</h3>
							<p class="services-text">We trim hedges and shrubs of all sizes.We have the tools to ensure</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="landscaping" class="services"/>
				
						<div class="home-blog-post">
							<h3 class="allServices">New Landscaping</h3>
							<p class="services-text">We can design and install your new landscapes, adding the personal touches that you require.</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="walls" class="services" />
							
						<div class="home-blog-post">
							<h3 class="allServices">Retaining Walls</h3>
							<p class="services-text">I never spend much time in school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten.</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="irrigation" class="services"/>
							
						<div class="home-blog-post">
							<h3 class="allServices">Irrigation Maintenance</h3>
							<p class="services-text">I never spend much time in school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten.</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="mulching" class="services" />
							
						<div class="home-blog-post">
							<h3 class="allServices">Mulching</h3>
							<p class="services-text">I never spend much time in school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten.</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="tree" class="services" />
				
						<div class="home-blog-post">
							<h3 class="allServices">Tree pruning or removal</h3>
							<p class="services-text">I never spend much time in school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten.</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="storm" class="services" />
							
						<div class="home-blog-post">
							<h3 class="allServices">Storm clean-up</h3>
							<p class="services-text">I never spend much time in school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten.</p>
						</div>
					</div>
				</div>

				<div class="four columns">
					<div class="home-blog">
						<img id="aerating" class="services" />
							
						<div class="home-blog-post">
							<h3 class="allServices">Aerating and overseeding</h3>
							<p class="services-text">I never spend much time in school but I taught ladies plenty. It's true I hire my body out for pay, hey hey. I've gotten.</p>
						</div>
					</div>
				</div>


			</div>
			
		</div>
			
	</div>

<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox();
	});
</script>

app/views/pages/portfolio.html.erb
<div class="container ">
	<h3 class="recent mt20">Our Portfolio</h3>
	<% @portfolio.each do |l| %>
		<div class="four columns">
			<div class="our-work">
				<%= link_to (l.url_large), :class => 'fancybox', :rel => 'group' do %>
  <%= image_tag(l.url_large, size: '220x220') %>
<% end %>
						<h3><%= truncate(l.title, :length => 20) %></h3>
					 </div>
			</div>
	<% end %>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox();
	});
</script>

app/views/shared/_footer.html.erb
<footer>
		<div class="container">
			<div class="eight columns">
				<h3>Contact information</h3>
				<p class="footer-text">
					13406 Misty Way,<br />
				  Fredericksburg, VA, 22407<br /><br />
				  Phone:<br>
				   +1 540-424-9535<br /><br />
			</div>
			<div class="eight columns">
				<div class="flickr clearfix">
					<h3>Social Media</h3>
					<a href="https://twitter.com/DC_Redneck/status/247034135196090368" target="_blank" >
						<img src="/assets/twitter.png" />
					</a>
					<a href="https://www.facebook.com/pages/Wellspring-Lawn-and-Landscape-Peter-Danaher/184149238279416" target="_blank">
						<img src="/assets/facebook.png" />
					</a>	
				</div>
			</div>
			<div class="sixteen columns">
				<hr class="line footer" />
			</div>
			<div class="eight columns">
				<div class="copyright">
					&copy; Copyright 2013
					<a href="index.html"></a>.
					
					
				</div>
			</div>
			
		</div>
	</footer>

	<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider({
		controlNav: true,
		animation: 'slide',
		pauseOnHover: true
	});
  });
</script>

app/views/shared/_header.html.erb
	<header>
		<div class="container">
			<div class="one-third column">
				<div class="logo">
					<a href="index.html">
						<img alt="logo" src="/assets/wellspringlogo.jpg">
					</a>
				</div>
			</div>
			<div class="two-thirds column">
				<nav id="menu" class="navigation">
					<ul id="nav" class="clearfix">
						<li>
							<%= link_to  root_path  do %>
                Home
                <span>Where We Live</span>
              <% end %>
						</li>
						<li>
							<%= link_to portfolio_path do %>
							 Portfolio
							 <span>See Our Work</span>
							 <% end %>
						</li>
						<li><a href="/contacts/new">Contact<span>Get In Touch</span></a></li>
					</ul>
				</nav>

				<!-- resp nav -->
         <select class="nav-select">
          <option value="selected">Take A Look Around...</option>
          <option value="<%= root_path %>">Home</option>
          <option value="<%= portfolio_path %>">Portfolio</option>
          <option value="<%= new_contact_path %>">Contact</option>
         </select>
        <!-- end resp nav -->
			</div>
			<div class="sixteen columns">
				<hr class="line" />
			</div>
		</div>
	</header>